name          'synyx-avahi'
version       '0.5.0'
source        'https://github.com/synyx/puppet-avahi'
author        'Florian Krupicka <krupicka@synyx.de>'
license       'Apache 2.0'
summary       'Install Avahi and manage mDNS configuration'
description   'Install Avahi and manage mDNS configuration'
project_page  'https://github.com/synyx/puppet-avahi'

dependency 'puppetlabs/stdlib'
